### ISSUE TITLE
Example send data doesn't work iOS 14.2

### ISSUE THREAD

**Issue by EbramTawfik** [ekasetiawans/flutter_background_service#21]
I am trying the example on iOS 14.2 and sendData doesn't work. `service.onDataReceived `never receive the data

**Comment by agent3bood** [comment]
Same as https://github.com/ekasetiawans/flutter_background_service/issues/19
You may try my branch

```
  flutter_background_service:
    git:
      url: git@github.com:agent3bood/flutter_background_service.git
      ref: agent3bood-patch-isServiceRunning
```
