### ISSUE TITLE
Android 14 issue with AndroidManifest

### ISSUE THREAD

**Issue by thaliachitziou99** [ekasetiawans/flutter_background_service#382]
I get this error:

`Manifest merger failed : Attribute service#id.flutter.flutter_background_service.BackgroundService@foregroundServiceType at AndroidManifest.xml:14:9-19:44 requires a placeholder substitution but no value for <foregroundServiceType> is provided.`

Any solution?

**Comment by ndungudedan** [comment]
I have overridden these dependencies causing the issue till I can figure out what's happening:

```yaml
dependency_overrides:
  flutter_background_service: 5.0.2
  flutter_background_service_android: 6.1.0
```
